### ISSUE TITLE
New semester

### ISSUE THREAD

**Issue by wudaown** [kenrick95/plan#12]
Hi, I came across your planner when search through the web and for some reason it is not working for the new semester. So i clone the code and run locally, make the changes in the php file. Format the 2017_1_exam_data.json using python and replace it. Then i realize not only is the exam_data.json wrong. It will be loading forever once the submit button is pressed. I have no knowledge at js and php hoping you can fix it or at least point out to me what is wrong the the 2017_1_data.json.

Below is the script I use to format the exam_data.json file. 
Thank you.

```
#!/usr/bin/python3
# _*_ coding:utf8 _*_

from bs4 import BeautifulSoup
import json

f = open('2017.html')
soup = BeautifulSoup(f)

f.close()

data = []
for i in soup.find_all('td'):
    data.append(i.text.strip('\n').strip(' '))


r = len(data)//6

d = dict()

for i in range(r):
    d.update( {data[3+i*6] : {'date':data[0+i*6],'day':data[1+i*6],'time':data[2+i*6],'code':data[3+i*6],'name':data[4+i*6],'duration':data[5+i*6]}})


for k,v in d.items():
    print(k,v)
    

with open('data.json','w') as outfile:
    json.dump(d,outfile)

```

**Comment by kenrick95** [comment]
Okay, data updated and deployed. Thanks for reporting!

It seems that the structure for exam data has changed and it has been fixed.

Note: both authors have graduated, though I intend to support this for the foreseeable future. Please notify us if there's something wrong or when data for new semester is posted. Thanks
