### ISSUE TITLE
Some Course Codes have no vacancy

### ISSUE THREAD

**Issue by ryotanada** [kenrick95/plan#19]
I have found an ideal schedule, but it turned out that the vacancy reads zero in the STARS Planner. Maybe you can add a feature to exclude certain course codes...

**Comment by kenrick95** [comment]
I'm sorry to hear that, but this tool is unable to access the index data from STARS Planner.

Thanks for the idea, but we're no longer actively developing new features and I only occasionally update the data to keep the application usable.

If you would like to have that feature, feel free to [fork the repo](https://help.github.com/en/articles/fork-a-repo) and develop it yourself. Thanks
