### ISSUE TITLE
error when using Get+Parse!

### ISSUE THREAD

**Issue by ZoTay** [kenrick95/plan#21]
Uncaught Error: Call to undefined function curl_init() in C:\Users\user\Downloads\planner\back_end\getter.php:8

**Comment by kenrick95** [comment]
Your PHP needs to have cURL extension enabled

**Comment by ZoTay** [comment]
thanks! now im getting "GET /getter.php - No such file or directory"

**Comment by ZoTay** [comment]
thanks!
