### ISSUE TITLE
Advanced Search not working properly

### ISSUE THREAD

**Issue by kombucha7** [kenrick95/plan#30]
Returns with "Server has returned an error. Please try again with different queries." when choosing timings despite having a valid combination with said timing.

![image](https://user-images.githubusercontent.com/29064557/143550335-112e4823-1004-4f07-a9f3-4956fb92095d.png)

I have checked that other days in advanced are all deselected and as seen in the picture there exists a combination where monday 830-9am is empty.

**Comment by kenrick95** [comment]
Thanks for the report. Looks like issue with server's PHP version (8.0). I've downgraded it to 7.4. and should be working again now. Please help to confirm :)

**Comment by kombucha7** [comment]
I've played around with it and got the usual "no combination error instead", which I assume means that the issue is resolved. Thanks for maintaining this.
