### ISSUE TITLE
"Server has returned an error. Please try again with different queries." 

### ISSUE THREAD

**Issue by Hexy06** [kenrick95/plan#31]
I keyed in my mods for sem2, excluding ICC as I can't find it on the list. The error message above was shown and i'm not sure why. 

The mods I keyed in are BS1005, BS1006, BS1007, BS1009, BS1100, CM1041.

**Comment by kenrick95** [comment]
This is caused by too many results found and the server does not have enough resources to serve the result. Now the result is capped at 10,000, but this also mean that the tool is probably not for you as you should be easily able to find your preferred schedule :)
